### ISSUE TITLE
Adding Home Mode switch

### ISSUE THREAD

**Issue by Pavion** [nibi79/synologysurveillancestation#16]
https://community.openhab.org/t/binding-request-synology-surveillance-station/8200/61

**Comment by grouchal** [comment]
+1

**Comment by Pavion** [comment]
Already implemented in the latest version, which is not yet released and could be found here:
https://github.com/nibi79/synologysurveillancestation/pull/20

**Comment by Pavion** [comment]
(Thing recreation required)

**Comment by Pavion** [comment]
Implemented with a20 release
