### ISSUE TITLE
Offline when restart

### ISSUE THREAD

**Issue by tnemrap** [nibi79/synologysurveillancestation#17]
When i restart openhab i always get OFFLINE - COMMUNICATION_ERROR Errorcode: 0

and i have 2 bindings
196 │ Active    │  80 │ 2.2.0.a16              │ SynologySurveillanceStation Bi
255 │ Installed │  80 │ 2.2.0                  │ SynologySurveillanceStation Bi

Only way to get it to work is delete 255 binding and delete and recreate items.

/Mike

**Comment by Pavion** [comment]
Most problems seem to come from connection timeouts. Please check the new version with increased timeout and more logging information here (just download/overwrite): 
https://github.com/nibi79/synologysurveillancestation/releases/tag/v0.17-alpha
I hope, I've got it, thanks for your patience :)
