### ISSUE TITLE
Dual bindings after restart

### ISSUE THREAD

**Issue by tnemrap** [nibi79/synologysurveillancestation#21]
I get this after restart

255 │ Active    │  80 │ 2.2.0.a20              │ SynologySurveillanceStation Bi
258 │ Installed │  80 │ 2.2.0                  │ SynologySurveillanceStation Bi

I uninstall 258 but after restart it is back.

**Comment by Pavion** [comment]
Could it be that you still have an older snapshot from a2 in your /addons folder? 
If so, please remove the older one (probably org.openhab.binding.synologysurveillancestation-2.2.0-20171219080000.jar) and try again.

**Comment by tnemrap** [comment]
Just have a20 jar in add-ons, can it be cached somewhere?

**Comment by Pavion** [comment]
I just can't reproduce this behavior :( 

I've tried to mix old and new files an a fresh 2.2 installation and the old binding gets removed as soon as I delete its file... 

I assume, you've already tried to `bundle:uninstall`, which actually should delete the cache (as in my test case). The last option would be cleaning the binding's cache manually. It should be located under `/userdata/cache/org.eclipse.osgi/258` (binding id) and should contain a `bundleFile` and `/lib` folder. Removing the whole folder has helped in my test case. 
**If you're going this way, please shutdown openHAB first and make a backup for sure.** 

I'm very sorry for the inconvenience.

**Comment by tnemrap** [comment]
after bundle:uninstall cache does not exist.
also have done a restart with cleared cache and tmp it still reappears.
196 │ Active  │  80 │ 2.2.0.a20              │ SynologySurveillanceStation Bi
256 │ Installed │  80 │ 2.2.0                  │ SynologySurveillanceStation Bi




'

**Comment by tnemrap** [comment]
find it 
it was an .jar in the addon directory that was not visible in winscp :(
