### ISSUE TITLE
Thread Snapshot: Connection timeout (4000 ms)

### ISSUE THREAD

**Issue by mrwee** [nibi79/synologysurveillancestation#23]
After upgrading to v21, I get many connection errors like:

> 2018-01-17 20:45:08.456 [ERROR] [tation.internal.thread.SynoApiThread] - Thread Snapshot: Connection timeout (4000 ms)

The camera is on-line/off-line all the time. I have enabled 'log:set DEBUG org.openhab.binding.synologysurveillancestation' but I don't see anything strange. The binding worked fine until the upgrade.

**Comment by Pavion** [comment]
This is a known issue (#15). Release v21 had no changes regarding connection handling, so this must be coincidence. If seldom, this error should not affect overall functionality. 

Connection timeout will be raised with the next release, which is not really a solution but a fix nonetheless. 

If you have this issue **real** often and could spend some time testing, I would ask you to help me find the cause. I could then either compile a version with an **excessive** logging in hope to pin down the issue or a version without / with very long timeout.

**Comment by mrwee** [comment]
ok, sorry had not noticed that it was known.. Of course I can help, that's the least I can do. You're doing all the hard work :).
I get it very often, so it would be great to get rid of. Let me know what I can do.

**Comment by mrwee** [comment]
ups, wrong button

**Comment by mrwee** [comment]
I can add that my DiskStation doesn't do much (so CPU utilization is low), it's on 1Gb LAN. OH2 runs on a virtual Windows 7 machine with plenty of ressources. So it could seem that it has something to do with the API perhaps? Is there any easy way of testing e.g. outside OH2 to rule that out?

**Comment by Pavion** [comment]
I will try to increase the timeout to 10 seconds but also trace and output to debug the time actually taken (unfortunately more spam). After that I send you a snapshot via forum PM, if that's fine with you. See you there!

**Comment by Pavion** [comment]
P.S. Are you using just one or several cameras?

**Comment by mrwee** [comment]
I have three, but only one is created in OH2 for now. Forum PM is quite fine :)

**Comment by Pavion** [comment]
New timeout concept seems to be stabler: https://github.com/nibi79/synologysurveillancestation/commit/9d479e2a15669a6ddb7366fd13c2d4f11ac08bcc
Thanks for testing @mrwee!
