### ISSUE TITLE
Trigger motion events from openhab

### ISSUE THREAD

**Issue by marco2901** [nibi79/synologysurveillancestation#31]
It would be cool to be able to trigger motion events from openhab (not manual recordings). Scenario: I have a motion detector, connected via KNX to opnhab and would like Surveillance Station to handle events of the motion detector like own motion events.
So, if motion events would not be read-only would help.

Thx!

**Comment by Pavion** [comment]
Yes, it's possible to pass events to Surveillance Station using following method:

`
https://your-IP:8070/webapi/entry.cgi?api=SYNO.SurveillanceStation.ExternalEvent&method="Trigger"&version=1&eventId=1&eventName="External"&account="name"&password="password"
`

For passed events a new action rule must be created, which would toggle the camera action record - thus actually toggling record switch. 

So why can't you just toggle your record switch with an openHAB rule? This would toggle the camera manual record, which is also visible in Surveillance Station. 

Note, that you can use the URI above in a HTTP binding if you're still interested in this solution.

**Comment by marco2901** [comment]
If I would just toggle manual record the disadvantge would be that I would not see the detected motion events in th surveillance station / DS Cam timeline view and I would not get a push notification "motion detected". Additionally I would also have to stop the recording "manually".

Thanks for your quick reply! I will test it!

**Comment by Pavion** [comment]
1) No, manual record is also shown in timeline
2) No, you wouldn't get a notification from Surveillance Station but you can easily send a notification from openHAB
3) No, quite the contrary. Synology API allows events to be triggered, but not to be "turned off", you can but set record duration in an action rule. Same behavior can be achieved with openHAB rule using Sleep:
```
rule "motion"
  when
    Item 'motiondetected' received command ON
  then
    sendMail("you@email.net", "Motion", "Motion detected")
    Surveillance_Recording.sendCommand(ON)
    Thread::sleep(14000) 
    Surveillance_Recording.sendCommand(OFF)
  end
```
As openHAB rules are more powerful, you can also implement advanced logic, such as other lamps, security devices and much more.

**Comment by Pavion** [comment]
see https://github.com/nibi79/synologysurveillancestation/releases/tag/v0.34-alpha

**Comment by marco2901** [comment]
Super cool, thanks!
