### ISSUE TITLE
surveillancestation got no handler attached

### ISSUE THREAD

**Issue by Hoffi96** [nibi79/synologysurveillancestation#33]
adding bridge to openhab brings the following error:

java.lang.IllegalStateException: Thing with UID synologysurveillancestation:station:a7cf1bd6 has no handler attached.

**Comment by Pavion** [comment]
Sorry, haven't seen it yet. Could you please provide more information?
- Please check if the binding is installed and running in Karaf (or in PaperUI > Configuration > Bindings).
- Are you using the latest version?
- Are you using text files or automatic discovery? Whichever you've tried, can you try the other method? 
- Please check whether your Thing's configuration is valid (as this exception occurs on configuring).
- Something else special with your setup?
- Anything else in openhab.log?

**Comment by Hoffi96** [comment]
Got the Problem. 
Something went wrong with the installation. The bundle couldnt start. After reinstall the bundle via console it works fine.
