### ISSUE TITLE
Binding not disconnecting

### ISSUE THREAD

**Issue by ritterr** [nibi79/synologysurveillancestation#42]
Just had a case open with Synology support and one of the issues having out of memory is apparently the root cause that the binding.
Quote:
<<Our developer had helped to update the Device  Package manually, and there's only 1 thing to remind, from our investigation, we found that the client device <IP> (home automation system) will only login DSM but will not log out.

This will cause many sessions accumulated and will consume many more resources causing potential system issues. Thus, please help to change the configuration settings from your automation system and make sure to log out after each session to DSM.>>

Regards Raphael

**Comment by grouchal** [comment]
If this is true - this could explain some problems on my synology too.

**Comment by Pavion** [comment]
I can confirm this behavior (although it seems to have no impact on my system). 
I'll look into it asap.

**Comment by Pavion** [comment]
Take a look at the latest fix
https://github.com/nibi79/synologysurveillancestation/releases

**Comment by Pavion** [comment]
if you disable your camera frequently, it may have bin the cause for too many connections
normally your SID should never change, so there is no reconnect
if still an issue, please contact me again
if not please confirm a solution

BR Pav

**Comment by ritterr** [comment]
I have just installed the lasted version of the binding, usually it would take up to a week for a OOM issue. Will keep you in the loop on the progress. Thank you for your efforts, regards
Raphael

**Comment by Pavion** [comment]
Hi @ritterr 
FYI: on my running machine I've now run into a strange issue with openHAB not responding anymore and spamming errors: `too many open files` after some time (~24 h). Although those errors are seemingly not related to the binding, it's the only thing I've changed so it may still be the root cause. Restarting OH fixes it for another day. 
If you encounter the same issue, please keep me updated. In the meantime I'll search deeper and report back asap.

**Comment by Pavion** [comment]
Small update: I've found an unrelated persistence error on my setup, which could also have been the cause. I've checked the code again and I don't see any leaks or unclosed resources. I'll stay on it.

**Comment by ritterr** [comment]
I am afraid to say, did not even take a day to have an OOM. Further to that the binding fills the logs:
2020-06-15 18:12:43.549 [ERROR] [b.core.service.AbstractActiveService] - Error while executing background thread HTTP Refresh Service
java.lang.NullPointerException: null
        at org.openhab.transform.javascript.internal.JavaScriptEngineManager.getScript(JavaScriptEngineManager.java:68) ~[?:?]
        at org.openhab.transform.javascript.internal.JavaScriptTransformationService.transform(JavaScriptTransformationService.java:74) ~[?:?]
        at org.openhab.core.transform.TransformationHelper$TransformationServiceDelegate.transform(TransformationHelper.java:69) ~[bundleFile:?]
        at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:218) ~[?:?]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:146) ~[bundleFile:?]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:169) [bundleFile:?]

Repetitive. If I remove the binding the messages have gone.
Restarted Openhab, starts filling the log again, happy to provide any logs. Any directions?

Regards Raphael

**Comment by Pavion** [comment]
I can confirm some weird behavior too I just can't find the root cause :(
This time I've got yet another exceptions which are still not directly related to the binding.
Do you also have some `Broken pipe` or `jetty`-related exceptions? 

I just don't understand why this issue it's so massive now although this binding is fairly old and run good for a while. Perhaps some changes with OH 2.5.5 I've recently upgraded to?!

Have you per chance your issues after upgrading or changing something?
If you have some clues or binding related entries, please keep me informed. 
I'll look further into the network code this week.

**Comment by Pavion** [comment]
@ritterr just to keep you up to date:

Yesterday I've removed this binding and restarted OH. 
After some time I'm still getting errors `Too many open files` and Karaf is not responding anymore.
I must now assume my installation somehow broken (2.5.5#104)... 
This week is rather crazy, but I'll try to find some time this weekend and look further.
Do you per chance encounter similar issues without this binding? Some new info/ideas?

**Comment by ritterr** [comment]
Apologies for the late reply. If I disable the binding the log messages have gone. Updated to the latest Master branch, enabled the binding and here:

java.lang.NullPointerException: null
        at org.openhab.transform.javascript.internal.JavaScriptEngineManager.getScript(JavaScriptEngineManager.java:68) ~[?:?]
        at org.openhab.transform.javascript.internal.JavaScriptTransformationService.transform(JavaScriptTransformationService.java:74) ~[?:?]
        at org.openhab.core.transform.TransformationHelper$TransformationServiceDelegate.transform(TransformationHelper.java:69) ~[bundleFile:?]
        at org.openhab.binding.http.internal.HttpBinding.execute(HttpBinding.java:218) ~[?:?]
        at org.openhab.core.binding.AbstractActiveBinding$BindingActiveService.execute(AbstractActiveBinding.java:146) ~[bundleFile:?]
        at org.openhab.core.service.AbstractActiveService$RefreshThread.run(AbstractActiveService.java:169) [bundleFile:?]

This message is continuously repeated. Anything I can do to support your troubleshooting?

**Comment by Pavion** [comment]
@ritterr, no bother, I'm happy that someone contributes 🙂 

As for the issue, I've run some tests yesterday...:

- this binding is using HttpClient provided by OH. It's the only instance, which is assigned at start and never changes. According to doc, this connection must also not be closed. I don't see anything left open.

- I've found two more minor errors both related to disabling camera:
    - disabled camera triggered the Thing OFFLINE/ONLINE all the time (higher load?)
    - triggering "Enable camera" toggled "Record" too and produced exceptions 

- I've run a test on a clean OH 2.5.5 stable for windows for about 12 hours monitoring handles:
    - at most 2 open socket connections to DS 
    - socket changes every 15 minutes (don't know why) but the connection to DS stays alive (same SID all the time, no login called)
    - constant number of file handles (about 150) 
    - constant CPU load

So far I'm not seeing any causes for this binding to produce higher load. 

Your initial issue was about frequent reconnecting and that should be solved by a latest release. 
Errors you're getting now are coming from the OH core. Could you please check the following:

- are you using Transformations on binding's items? Your exception seem to come from there. Please comment out any Items using it and try restart

See also: 
https://community.openhab.org/t/javascript-receiving-error-when-getting-messages-from-a-shelly-device/100941
https://community.openhab.org/t/js-transformation-stopped-working-after-upgrade-to-2-5-6-snapshot-131/99705/11

- if you're not using JS Transformation, please try to uninstall the corresponding service
- are you're disabling / enabling your camera often?
- are you using sitemaps? I've seen some hints about IMAGE items leaking there. Please comment out any sitemaps items and try restart
- are you still having memory leaks (after doing things above)? 
- is this exception breaking for the binding? If yes: goes the binding offline? Could you then enable TRACE for this binding and provide larger log excerpt (PM / Mail, please remove/replace your credentials first).

**Comment by Pavion** [comment]
_purge old issues, please reopen if needed_
