### ISSUE TITLE
Image not updating

### ISSUE THREAD

**Issue by grouchal** [nibi79/synologysurveillancestation#43]
I seem to be stuck with a very old image - have restarted openhanded and it makes no difference.

The binding it working as I get values from the Surveillance Station for movement etc - just the image never updates.

Am using latest version.

Openhab 2.5.10

Add-on: 2.5.6-SNAPSHOT.jar

**Comment by Pavion** [comment]
I just had some weird issues myself but after updating to OH 2.5.10 and restarting everything works again. 
Some ideas: 
- have you any related messages in your log? 
    - you can check advanced info using `log:set DEBUG org.openhab.binding.synologysurveillancestation` (just don't forget to set it back to ERROR later)
- have you tried manual refresh in PaperUI?
    - if worked, have you checked your snapshot timeout?
- is your bridge using IPv4 or IPv6?

Meanwhile I'll keep an eye on it.
