### ISSUE TITLE
Error 103 with recent updates

### ISSUE THREAD

**Issue by kabili207** [nibi79/synologysurveillancestation#47]
I've started getting the following error with recent versions of surveillance station. I'm not exactly sure *when* it broke since I went quite a few months without update my NAS (bad practice, I know).
```
[ERROR] [nternal.webapi.request.SynoApiRequest] - RESPONSE: {"error":{"code":103},"success":false}
```

**Comment by Pavion** [comment]
103 should mean "Method does not exist", so some API call might be broken.  
Especially if you've updated your DSM to 7.0 please check whether you're using the latest release of this binding.
```
Active  x  80 x 3.1.0.202101291345    x openHAB Add-ons :: Bundles :: Synology Surveillance Station Binding
```
If it still not works, please enable DEBUG in Karaf: 
```
log:set DEBUG org.openhab.binding.synologysurveillancestation
```
In your openhab.log you'll then see the URLs being called (and failing). Please send me a larger log excerpt then. 
(Please remember to set log level back to ERROR afterwards).

**Comment by kabili207** [comment]
I feel like an idiot. I was one version behind on the binding.
Updated and fixed. Sorry for bothering you with something so simple.
