### ISSUE TITLE
Unable to connect, DSM 7.1.1, SS 9.0.2

### ISSUE THREAD

**Issue by tcgerhard** [nibi79/synologysurveillancestation#54]
I am running the current version from the marketplace
`301 │ Active │  80 │ 3.3.0.202207031140     │ openHAB Add-ons :: Bundles :: Synology Surveillance Station Binding`
on the 3.3.0 Release Build.
DSM version is `DSM 7.1.1-42962 Update 1`
Surveillance Station version is `9.0.2-10057`

I had installed the addon  previously on an older version of OH and subsequently deleted it, leaving some orphan things behind (I don't think this is pertinent, but including just in case); the old things were deleted except for a bridge, which had its config updated to match current IP address and credentials of my NAS.

DEBUG log shows 
`2022-11-24 22:01:46.262 [DEBUG] [ternal.webapi.request.SynoApiRequest] - URI: http://10.1.3.60:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=2&method=Login&_sid=&passwd=REDACTED&session=SurveillanceStation&format=sid&account=REDACTED
2022-11-24 22:01:46.268 [ERROR] [ternal.webapi.request.SynoApiRequest] - RESPONSE: {"error":{"code":103},"success":false}`

Error 103 is `Method does not exist`.
In testing with CURL, I had to both raise the API version from 2 to 3 and change the spelling of the method parameter to 'login' (all lower case).

Perhaps more recent versions of the API have become more strict about the method parameter?

**Comment by Pavion** [comment]
Well... I admit I'm confused. I have all the same versions and my test setup is also 3.3.0 STABLE. 
```
bundle:list | grep Sy
240 │ Active │  80 │ 3.3.0.202207031140     │ openHAB Add-ons :: Bundles :: Synology Surveillance Station Binding
``` 
But in my case the proper version 6 is called: 
```
15:30:56.955 [DEBUG] [nternal.webapi.request.SynoApiRequest] - URI: http://192.168.0.11:5000/webapi/auth.cgi?api=SYNO.API.Auth&version=6&method=Login&_sid=&passwd=mypass&session=SurveillanceStation&format=sid&account=myname
RESPONSE: {"data":{"did":"aBzZPj_KwwwrdkgOyXXmJiuP-fsdf2ewrq-SFMua6kIemBPyS-qwer-qwerqwerdsaAwqeeqw","is_portal_port":false,"sid":"qwertyqwertyqwertyblahBlahBLAH"},"success":true}
```

You can see this version in the source code here: 
https://github.com/nibi79/synologysurveillancestation/blob/3b09682d51884bb411beab05f5e9c769747790c9/src/main/java/org/openhab/binding/synologysurveillancestation/internal/webapi/request/SynoApiAuth.java#L43

Could you please check whether you're having an older version still installed?
If not, please try to recreate your Bridge from scratch although it shouldn't have the impact... 
If possible, please try to reinstall the binding or try to make a clean setup for test purposes.

**Comment by tcgerhard** [comment]
My apologies.    Apparently I had installed the 3.0.0 version via the addons directory and missed it when I scanned bundle:list.    Looks like it's running well now.,
