### ISSUE TITLE
Upgrade to openHAB 4.0

### ISSUE THREAD

**Issue by jlaur** [nibi79/synologysurveillancestation#55]
Are you considering upgrading to 4.0? Perhaps you can provide build instructions, somehow I didn't manage to build it.

**Comment by Pavion** [comment]
Please check the new release here
https://github.com/nibi79/synologysurveillancestation/releases/tag/4.0.0.202304021037
Feedback is appreciated!

**Comment by jlaur** [comment]
Thanks, it works!
