### ISSUE TITLE
Upgrade to openHAB 4.1

### ISSUE THREAD

**Issue by jlaur** [nibi79/synologysurveillancestation#57]
openHAB is due to release in a few weeks:
https://community.openhab.org/t/openhab-4-1-milestone-builds/149501/4

Any chance to see an update? 🙂

**Comment by Pavion** [comment]
Is https://github.com/nibi79/synologysurveillancestation/releases/tag/4.0.0.202304021037 not working with 4.1?

**Comment by jlaur** [comment]
@Pavion - sorry, you are right, it does. I didn't expect that because of some changes that broke many other binding JARs that needed to be recompiled. Apparently your binding is not affected.
