### ISSUE TITLE
OH 4.x binding supporting DSM 6.x

### ISSUE THREAD

**Issue by fanievh** [nibi79/synologysurveillancestation#59]
Hi,

Have been using your binding successfully for a while and thanks for creating and maintaining it.  Would it be possible to create a build that runs on OH 4.x that supports DSM 6.x?  If yes, would appreciate it very much as I'm still running Synology hardware that doesn't support DSM 7.x.

**Comment by Pavion** [comment]
Hi @fanievh! 
Please check the latest release:
https://github.com/nibi79/synologysurveillancestation/releases/tag/4.3.0.202408251325
Sorry but I'm unable to test it. I had to push to 4.3 and then reapplied the old DSM6 downgrade, so it might just work.  
As always, please remove old release first. If migrating from OH3 to OH4 Things need to be recreated.  
Feedback appreciated.

**Comment by fanievh** [comment]
Hi @Pavion I tested it with the functionality that I use which is camera snapshots and it works! Thank you for creating this build

**Comment by Pavion** [comment]
Perfect! Thank you for your feedback!
