### ISSUE TITLE
check whether own thing.xml for PTZ cameras or not

### ISSUE THREAD

**Issue by nibi79** [nibi79/synologysurveillancestation#6]
https://www.eclipse.org/forums/index.php/m/1774837/#msg_1774837

**Comment by Pavion** [comment]
Declaring specific things for different camera types is a swamp I wouldn't go into yet. There is also no risk in allowing PTZ on non-PTZ cameras. 
My proposal would be declaring PTZ (and such) channels with `advanced="true"` attribute, which would disable an automatic item creation in PaperUI and force an user to map items only when needed.

**Comment by nibi79** [comment]
I agree with you so let us implement your proposal
